name: hotp
description: An implementation of the HMAC-based One-time Password (HOTP).
version: 0.1.0
homepage: https://github.com/odroe/otp/tree/main/hotp
repository: https://github.com/odroe/otp

environment:
  sdk: ^3.4.3

dependencies:
  base32: ^2.1.3
  crypto: ^3.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
